# Generated by Django 5.2.7 on 2025-10-03 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppOAuthCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_mail', models.EmailField(max_length=255)),
                ('google_oauth2_client_id', models.CharField(max_length=255)),
                ('google_oauth2_client_secret', models.CharField(max_length=255)),
                ('google_ads_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_ads_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('google_ads_refresh_token', models.TextField(blank=True, null=True)),
                ('google_ad_manager_network_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_oauth_credentials',
            },
        ),
    ]