# Generated by Django 5.2.7 on 2025-10-03 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppOAuthCredentials',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False, max_length=11)),
                ('account_name', models.CharField(max_length=255)),
                ('user_mail', models.EmailField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('network_code', models.CharField(blank=True, max_length=50, null=True)),
                ('developer_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('mdb', models.CharField(max_length=36)),
                ('mdb_name', models.CharField(max_length=255)),
                ('mdd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_credentials',
            },
        ),
    ]