# Generated by Django 4.2.25 on 2025-10-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoauthcredentials',
            name='account_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appoauthcredentials',
            name='developer_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appoauthcredentials',
            name='network_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
