# Generated by Django 4.2.25 on 2025-11-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_appoauthcredentials_account_id_and_more'),
        ('management', '0003_add_sample_data'),
    ]

    operations = [
    ]
